# Generated by Django 3.0.5 on 2020-06-12 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0003_auto_20200612_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
